name: Releaace-and-Deploy

on: 
  push:
    tags:
      - 'v*' ## 监听以v开头的标签
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: create-release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Automated release based on tag ${{ github.ref }}
            ## Changes
            - Feature A
            - Bug fix B
          draft: false
          prerelease: false

      - name: deploy-try
        run: |
          echo "🚀 Deploying version ${{ github.ref }} to Production..." 